version: '3.3'
services:
  local-aws:
    init: true
    image: local-aws
    build:
      context: .
    environment:
      - RUST_LOG=aws_smithy_http=debug,aws_config=debug,aws_sigv4=debug,app=debug
      - "SAM_TEMPLATE=$SAM_TEMPLATE"
    ports:
      - "3000:3000"
    mem_limit: 250m
    networks:
      - development
    volumes:
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

  # test-lambda-1:
  #   init: true
  #   image: test-lambda-1
  #   build:
  #     context: ./test-lambda-1
  #   environment:
  #     # Containers process requests based on the {api-gateway-url}/{container-name}
  #     - AWS_LAMBDA_RUNTIME_API=http://local-api-gateway:3000/test-lambda-1
  #     - AWS_LAMBDA_FUNCTION_NAME=TestLambda1
  #     - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=50
  #     - AWS_LAMBDA_FUNCTION_VERSION=1
  #     - AWS_LAMBDA_LOG_STREAM_NAME=TestLambda1
  #     - AWS_LAMBDA_LOG_GROUP_NAME=aws/lambda/TestLambda1
  #   depends_on:
  #     - "local-api-gateway"
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - development
  #
  # test-add-message:
  #   init: true
  #   image: test-add-message
  #   build:
  #     context: ./test-add-message
  #   environment:
  #     # Containers process requests based on the {api-gateway-url}/{container-name}
  #     - AWS_LAMBDA_RUNTIME_API=http://local-api-gateway:3000/test-add-message
  #     - AWS_LAMBDA_FUNCTION_NAME=AddMessage
  #     - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=50
  #     - AWS_LAMBDA_FUNCTION_VERSION=1
  #     - AWS_LAMBDA_LOG_STREAM_NAME=AddMessage
  #     - AWS_LAMBDA_LOG_GROUP_NAME=aws/lambda/AddMessage
  #   depends_on:
  #     - "local-api-gateway"
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - development
  #   volumes:
  #     - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro
  #
  # test-lambda-2:
  #   init: true
  #   image: test-lambda-2
  #   build:
  #     context: ./test-lambda-2
  #   environment:
  #     # Containers process requests based on the {api-gateway-url}/{container-name}
  #     - "AWS_LAMBDA_RUNTIME_API=http://local-api-gateway:3000/test-lambda-2"
  #   depends_on:
  #     - "local-api-gateway"
  #   deploy:
  #     replicas: 1
  #   networks:
  #     - development
  #
  # sqs-local:
  #   init: true
  #   image: softwaremill/elasticmq:1.3.14
  #   ports:
  #     - "9324:9324"
  #     - "9325:9325"
  #   networks:
  #     - development

networks:
  development:
    attachable: true


