version: '3.9'
services:
  local-aws:
    init: true
    # image: local-aws
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=aws_smithy_http=debug,aws_config=debug,aws_sigv4=debug,app=trace
      - SAM_TEMPLATE=$SAM_TEMPLATE
    networks:
      - development
    ports:
      - 3030:3030
    mem_limit: 250m
    volumes:
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

  test-lambda-node:
    init: true
    image: test-lambda-node
    build:
      context: ./test-lambda-node
    environment:
      # Containers process requests based on the {api-gateway-url}/{container-name}
      - AWS_LAMBDA_RUNTIME_API=http://local-aws:3030/test-lambda-node
    depends_on:
      - local-aws
    deploy:
      replicas: 1
    networks:
      - development

  test-axum:
    init: true
    image: test-axum
    build:
      context: ./test-axum
      dockerfile: Dockerfile
    environment:
      # - RUST_LOG=aws_smithy_http=trace,aws_config=trace,aws_sigv4=trace,app=trace,lambda_runtime=trace
      - RUST_LOG=trace
      # - RUST_BACKTRACE=1
      - AWS_LAMBDA_RUNTIME_API=http://local-aws:3030/test-axum
      - AWS_LAMBDA_FUNCTION_NAME=TestAxum
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=50
      - AWS_LAMBDA_FUNCTION_VERSION=1
      - AWS_LAMBDA_LOG_STREAM_NAME=TestAxum
      - AWS_LAMBDA_LOG_GROUP_NAME=aws/lambda/TestAxum
    depends_on:
      - local-aws
    deploy:
      replicas: 1
    networks:
      - development

  test-rust:
    init: true
    image: test-rust
    build:
      context: ./test-basic-rust
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=aws_smithy_http=trace,aws_config=trace,aws_sigv4=trace,app=trace
      - AWS_LAMBDA_RUNTIME_API=http://local-aws:3030/test-rust
      - AWS_LAMBDA_FUNCTION_NAME=TestRust
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=50
      - AWS_LAMBDA_FUNCTION_VERSION=1
      - AWS_LAMBDA_LOG_STREAM_NAME=TestRust
      - AWS_LAMBDA_LOG_GROUP_NAME=aws/lambda/TestRust
    depends_on:
      - local-aws
    deploy:
      replicas: 1
    networks:
      - development

networks:
  development:
    attachable: true


