version: '3.9'
services:
  local-aws:
    init: true
    # image: local-aws
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=aws_smithy_http=debug,aws_config=debug,aws_sigv4=debug,app=debug
      - "SAM_TEMPLATE=$SAM_TEMPLATE"
    networks:
      - development
    ports:
      - 3000:3000
    mem_limit: 250m
    volumes:
      - /home/ubuntu/.aws/credentials:/root/.aws/credentials:ro

networks:
  development:
    attachable: true


