version: '3.3'
services:
  sam-e-invoker:
    init: true
    image: sam-e-invoker
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - RUST_LOG=debug
      - "CONFIG=$CONFIG"
    ports:
      - 3000:3000
      - 3030:3030
