Transform: AWS::Serverless-2016-10-31
Resources:
  TestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Test
      Description: Test
      StageName: Prod
    Domain:
      DomainName: Test
      CertificateArn: Test

  SnapasAuthAppApiDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: Test
      RestApiId: TestApiGateway
      BasePath: axum
      Stage: !Ref TestApiGateway.Stage
  TestAxum:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64      
      ImageUri: test-axum
      Events:
        Main:
          Type: Api
          Properties:
            RestApiId: !Ref TestApiGateway
            Path: /
            Method: ANY
        Main:
          Type: Api
          Properties:
            RestApiId: !Ref TestApiGateway
            Path: /{path+}
            Method: ANY
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TestDeliverySQS.Arn
            BatchSize: 10
      Timeout: 30
      MemorySize: 50
  TestRust:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64      
      ImageUri: test-rust
      Events:
        Main:
          Type: Api
          Properties:
            Path: /test-rust-route
            Method: ANY
  TestLambdaNode:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64      
      ImageUri: test-lambda-node
      Events:
        Main:
          Type: Api
          Properties:
            Path: /test-lambda-node-route
            Method: ANY
        # MySQSSecondEvent:
        #   Type: SQS
        #   Properties:
        #     Queue: !GetAtt AThirdTestSQS.Arn
        #     BatchSize: 8
  # AddMessage:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     PackageType: Image
  #     Architectures:
  #       - arm64      
  #     ImageUri: test-add-message
  #     Events:
  #       Main:
  #         Type: Api
  #         Properties:
  #           Path: /add-message
  #           Method: ANY
  # TestDeliverySQS:
  #   Type: AWS::SQS::Queue
  #   Properties:
  #     QueueName: TestDeliverySQS
  # TestANewDeliverySQS:
  #   Type: AWS::SQS::Queue
  #   Properties:
  #     QueueName: TestANewDeliverySQS
  # AThirdTestSQS:
  #   Type: AWS::SQS::Queue
  #   Properties:
  #     QueueName: AThirdTestSQS

