[workspace]
[package]
name = "sam-e-common"
version = "0.1.0"
description = "A crate to house common functions across the SAM-E ecosystem."
edition = "2021"

[dependencies]

[[bin]]
name = "app"
path = "src/main.rs"

