Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvironmentName:
    Description: The environment name is determined by the current branch you are deploying from.
    Type: String
    Default: staging

Resources:
  TestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Test_Name
      Description: Test
      StageName: Prod
    Domain:
      DomainName: Test
      CertificateArn: Test

  AppApiDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: Test
      RestApiId: TestApiGateway
      BasePath: axum
      Stage: 
        Ref: TestApiGateway.Stage

  TestAxum:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64      
      ImageUri: test-axum
      Events:
        Index:
          Type: Api
          Properties:
            RestApiId: 
              Ref: TestApiGateway
            Path: /
            Method: ANY
        Main:
          Type: Api
          Properties:
            RestApiId: TestApiGateway
            Path: /{path+}
            Method: ANY
      Timeout: 30
      MemorySize: 50
      Environment:
        Variables:
          TEST_VAR: testing
