version: '3.9'

networks:
  development:
    attachable: true

services:
  sam-e-invoker:
    init: true
    build:
      context: ~/Work/sam-e # TODO: obviously this is wrong and should come from dockerhub
      dockerfile: Dockerfile.release
    environment:
      - RUST_LOG=aws_smithy_http=debug,aws_config=debug,aws_sigv4=debug,app=trace
      - CONFIG=$CONFIG
    networks:
      - development
    ports:
      - 3000:3000
    mem_limit: 250m
{% for lambda in lambdas %}
  {{lambda.name}}:
    init: true
    image: {{lambda.image}}
    networks:
      - development
    deploy:
      replicas: 1
    depends_on:
      - sam-e-invoker
    environment:
      - AWS_LAMBDA_RUNTIME_API=http://sam-e-invoker:3000/{{lambda.name}}
      - AWS_LAMBDA_FUNCTION_NAME={{lambda.name}}
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=50
      - AWS_LAMBDA_FUNCTION_VERSION=1
      - AWS_LAMBDA_LOG_STREAM_NAME={{lambda.name}}
      - AWS_LAMBDA_LOG_GROUP_NAME=aws/lambda/{{lambda.name}}
      {% for key, value in lambda.environment_vars -%}
      - {{key}}={{value}}
      {% endfor -%}
{% endfor -%}
