version: '3.9'

networks:
  development:
    name: development
    external: true

services:
  # *********************** Custom lambdas ***************************
  # Each of the lambda functions is run as a separate docker container that will communicate with the local invoker
{% for lambda in lambdas %}
  {{lambda.name}}:
    init: true
    image: {{lambda.image}}
    networks:
      - development
    deploy:
      replicas: 1
    environment:
      - AWS_LAMBDA_RUNTIME_API=http://sam-e-invoker:3000/{{lambda.name}}
      - AWS_LAMBDA_FUNCTION_NAME={{lambda.name}}
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=50
      - AWS_LAMBDA_FUNCTION_VERSION=1
      - AWS_LAMBDA_LOG_STREAM_NAME={{lambda.name}}
      - AWS_LAMBDA_LOG_GROUP_NAME=aws/lambda/{{lambda.name}}
      {% for key, value in lambda.environment_vars -%}
      - {{key}}={{value}}
      {% endfor -%}
{% endfor %}
